### ISSUE TITLE
Should appsettings values be changed?

### ISSUE THREAD

**Issue by virshu** [aws-samples/bobs-used-bookstore-sample#35]
Not sure if it is *my* misunderstanding or something is missing in the application. `appsettings.json` has placeholders, such as `"CognitoDomain": "[Retrieved from AWS Systems Manager Parameter Store]"`

When I am running in Integrated mode, these are the values that are assigned:
`_cognitoDomain = builder.Configuration["Authentication:Cognito:CognitoDomain"];`

And the application can't retrieve values from System Manager's Parameter Store, nor authenticate against Cognito. I don't see any code where it actually goes to SSM and retrieves the values... Am I missing something?

Thanks,

**Comment by bradwebber** [comment]
Hi @virshu , did you set up the AWS services required for integrated debugging by running `cdk deploy BobsBookstoreCore` ?

**Comment by virshu** [comment]
Yes of course! I can see that all parameters are created:
![image](https://github.com/aws-samples/bobs-used-bookstore-sample/assets/4563719/794e34f1-8931-41e2-acb4-cd72981a1226)

but `AuthenticationSetup:ConfigureAuthentication` doesn't retrieve them:
![image](https://github.com/aws-samples/bobs-used-bookstore-sample/assets/4563719/d76ec81b-2752-48a3-bed8-395256914235)

I'll create a minimal example. Maybe something is wrong with AWS profile in appsettings. I don't see that code retrieves any values from SSM:
![image](https://github.com/aws-samples/bobs-used-bookstore-sample/assets/4563719/6b86712c-4073-46af-a20d-f36e38d567d4)

**Comment by virshu** [comment]
I figured out the problem (once I removed `optional=true` I started getting exceptions, instead of silently failing). My profile was configured as SSO from some other work that I was doing. Once I removed references to SSO, it worked. Thank you

**Comment by bradwebber** [comment]
Thanks for the update @virshu , great to hear you were able to identify the issue.
